site_name: Everything About Python
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
