[project]
name = "everything-i-know-about-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipython>=9.4.0",
    "pandas>=2.3.2",
    "pre-commit>=4.3.0",
]
